<?xml version="1.0" ?>
<!DOCTYPE tests [
  <!ELEMENT tests (test)+>
  <!ATTLIST tests
            totalpoints CDATA "100">
  <!ELEMENT test (#PCDATA)>
  <!ATTLIST test
            id         ID            #REQUIRED
            cleardata  (true|false)  "true"
            fpoints    CDATA         "3"
            fnext      IDREF         #IMPLIED>
]>

<!-- Project Part 1 -->

<tests totalpoints="100">

  <!-- Basic tests -->


  <test id="Faddcmtdierd" fnext="Fdieb4" fpoints="15">
After failure, previous committed transactions are lost.
  </test>

  <test id="Fadddierd" fpoints="5">
After failure, transaction is not forcibly aborted.
  </test>

  <test id="Fadddiexid" fpoints="1">
Forcibly aborted transaction does not throw TransactionAbortedException.
  </test>

  <test id="Fdieb4" fnext="Fdieaft" fpoints="10">
dieBeforePointerSwitch fails.
  </test>

  <test id="Fdieb4cmt" fnext="Fdieaft" fpoints="10">
After dieBeforePointerSwitch is set, server does not die during commit.
  </test>

  <test id="Fdieb4self" fnext="Fdieaft" fpoints="10">
After dieBeforePointerSwitch, transaction is not forcibly aborted, or previous committed transactions are lost.
  </test>

  <test id="Fdieb4other" fpoints="5">
After dieBeforePointerSwitch, other transaction is not forcibly aborted.
  </test>

  <test id="Fdieaft" fnext="_END_" fpoints="10">
dieAfterPointerSwitch fails.
  </test>

  <test id="Fdieaftcmt" fnext="_END_" fpoints="10">
After dieAfterPointerSwitch is set, server does not die during commit.
  </test>

  <test id="Fdieaftself" fnext="_END_" fpoints="10">
After dieAfterPointerSwitch, transaction is not committed, or previous committed transactions are lost.
  </test>

  <test id="Fdieaftother" fpoints="5">
After dieAfterPointerSwitch, other transactions are not forcibly aborted.
  </test>

</tests>
